apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant-label
  template:
    metadata:
      labels:
        app: homeassistant-label
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: wysehub-worker-1
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:latest
        env:
        - name: TZ
          value: "Europe/Bucharest"
        ports:
          - containerPort: 8123
        resources: {}
        volumeMounts:
          - mountPath: /config
            name: homeassistant-config
          # - mountPath: /etc/localtime
          #   name: homeassistant-time
          #   readOnly: true
      restartPolicy: Always
      volumes:
        - name: homeassistant-config
          persistentVolumeClaim:
            claimName: homeassistant-config
        # - name: homeassistant-pv-time
        #   persistentVolumeClaim:
        #     claimName: homeassistant-time
        #     readOnly: true
status: {}
