## Homeassistant Service ###
apiVersion: v1
kind: Service
metadata:
  name: haas-service
  namespace: homeassistant
  annotations:
    metallb.universe.tf/allow-shared-ip: "haas-shared-ip"
spec:
  selector:
    app: haas
  ports:
  - name: homeassistant
    port: 8123
    targetPort: 8123
  type: LoadBalancer
  loadBalancerIP: 10.100.99.89