## MQTT Service ###
apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
  namespace: homeassistant
  annotations:
    metallb.universe.tf/allow-shared-ip: "haas-shared-ip"
spec:
  selector:
    app: mqtt1883
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  -
  type: LoadBalancer
  loadBalancerIP: 10.100.99.89